# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.runs/synth_2/.Xil/Vivado-18072-DESKTOP-PVEE1TC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/6cfa/hdl
    g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog
    g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog
  } {
      G:/xillinx/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      G:/xillinx/2025.1/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      G:/xillinx/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_2/synth/bd_49ec_arsw_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_3/synth/bd_49ec_rsw_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_4/synth/bd_49ec_awsw_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_5/synth/bd_49ec_wsw_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_6/synth/bd_49ec_bsw_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/d800/hdl/sc_mmu_v1_0_vl_rfs.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_7/synth/bd_49ec_s00mmu_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_8/synth/bd_49ec_s00tr_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/dce3/hdl/sc_si_converter_v1_0_vl_rfs.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_9/synth/bd_49ec_s00sic_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_10/synth/bd_49ec_s00a2s_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/sc_node_v1_0_vl_rfs.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_11/synth/bd_49ec_sarn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_12/synth/bd_49ec_srn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_13/synth/bd_49ec_sawn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_14/synth/bd_49ec_swn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_15/synth/bd_49ec_sbn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_16/synth/bd_49ec_s01mmu_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_17/synth/bd_49ec_s01tr_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_18/synth/bd_49ec_s01sic_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_19/synth/bd_49ec_s01a2s_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_20/synth/bd_49ec_sarn_1.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_21/synth/bd_49ec_srn_1.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_22/synth/bd_49ec_sawn_1.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_23/synth/bd_49ec_swn_1.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_24/synth/bd_49ec_sbn_1.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_25/synth/bd_49ec_m00s2a_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_26/synth/bd_49ec_m00arn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_27/synth/bd_49ec_m00rn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_28/synth/bd_49ec_m00awn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_29/synth/bd_49ec_m00wn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_30/synth/bd_49ec_m00bn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/0133/hdl/sc_exit_v1_0_vl_rfs.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_31/synth/bd_49ec_m00e_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_32/synth/bd_49ec_m01s2a_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_33/synth/bd_49ec_m01arn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_34/synth/bd_49ec_m01rn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_35/synth/bd_49ec_m01awn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_36/synth/bd_49ec_m01wn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_37/synth/bd_49ec_m01bn_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_38/synth/bd_49ec_m01e_0.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/ipshared/cfe6/src/avg_pooling.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/ipshared/cfe6/src/dense_layer.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/ipshared/cfe6/src/dense_layer1.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/ipshared/cfe6/src/dense_layer2.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/ipshared/cfe6/src/neural_network.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/ipshared/cfe6/hdl/neural_network_v1_0_S00_AXI.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/ipshared/cfe6/src/neuron.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/ipshared/cfe6/src/relu.sv
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/ipshared/cfe6/src/select_max.sv
    }
      rt::read_verilog -include {
    g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/6cfa/hdl
    g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog
    g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog
  } {
      G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/synth/design_1.v
    }
      rt::read_verilog -include {
    g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/6cfa/hdl
    g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog
    g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog
  } {
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/4f12/hdl/verilog/processing_system7_v5_5_aw_atc.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/4f12/hdl/verilog/processing_system7_v5_5_b_atc.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/4f12/hdl/verilog/processing_system7_v5_5_w_atc.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/4f12/hdl/verilog/processing_system7_v5_5_atc.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/4f12/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_2/hdl/verilog/processing_system7_v5_5_processing_system7.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_2/synth/design_1_processing_system7_0_2.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_0/synth/bd_49ec_one_0.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/synth/bd_49ec.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/synth/design_1_smartconnect_0_3.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/ipshared/cfe6/hdl/neural_network_v1_0.v
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/ip/design_1_neural_network_0_3/synth/design_1_neural_network_0_3.v
    }
      rt::read_vhdl -lib xpm G:/xillinx/2025.1/Vivado/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_17 g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_2/synth/design_1_proc_sys_reset_0_2.vhd
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_1/synth/bd_49ec_psr_aclk_0.vhd
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_1/synth/design_1_axi_bram_ctrl_0_1.vhd
      g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/synth/design_1_blk_mem_gen_0_0.vhd
    }
      rt::read_vhdl -lib axi_bram_ctrl_v4_1_13 g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/2f03/hdl/axi_bram_ctrl_v4_1_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_11 g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ipshared/a32c/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.runs/synth_2/.Xil/Vivado-18072-DESKTOP-PVEE1TC/realtime/design_1_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top design_1_wrapper
    rt::set_parameter incrementalOnCache "G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.runs/synth_2/.Xil/Vivado-18072-DESKTOP-PVEE1TC/refSynth"
    rt::set_parameter doIncremental true
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.runs/synth_2/.Xil/Vivado-18072-DESKTOP-PVEE1TC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
