# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.runs/synth_2/design_1_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_2" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param synth.incrementalSynthesisCache C:/Users/pratyush/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-22612-DESKTOP-PVEE1TC/incrSyn
set_param checkpoint.writeSynthRtdsInDcp 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.cache/wt [current_project]
set_property parent.project_path G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/pratyush/AppData/Roaming/Xilinx/Vivado/2025.1/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/Users/pratyush/AppData/Roaming/Xilinx/ip_repo
  g:/zed_board/F/neural_network_1_0
} [current_project]
update_ip_catalog
set_property ip_output_repo g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_2/design_1_processing_system7_0_2.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_2/design_1_proc_sys_reset_0_2_board.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_1/bd_49ec_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_2/bd_49ec_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_3/bd_49ec_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_4/bd_49ec_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_5/bd_49ec_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_6/bd_49ec_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_10/bd_49ec_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_11/bd_49ec_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_12/bd_49ec_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_13/bd_49ec_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_14/bd_49ec_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_15/bd_49ec_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_19/bd_49ec_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_20/bd_49ec_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_21/bd_49ec_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_22/bd_49ec_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_23/bd_49ec_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_24/bd_49ec_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_25/bd_49ec_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_26/bd_49ec_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_27/bd_49ec_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_28/bd_49ec_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_29/bd_49ec_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_30/bd_49ec_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_32/bd_49ec_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_33/bd_49ec_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_34/bd_49ec_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_35/bd_49ec_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_36/bd_49ec_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_37/bd_49ec_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/smartconnect.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/design_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/constrs_1/new/design.xdc
set_property used_in_implementation false [get_files G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/constrs_1/new/design.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental G:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/utils_1/imports/synth_2/design_1_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_wrapper -part xc7z020clg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_2" END { }
