# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/design.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_2/design_1_processing_system7_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_2 || ORIG_REF_NAME==design_1_processing_system7_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_2/design_1_proc_sys_reset_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_2 || ORIG_REF_NAME==design_1_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_3/design_1_smartconnect_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_3 || ORIG_REF_NAME==design_1_smartconnect_0_3} -quiet] -quiet

# Block Designs: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/bd_49ec.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_0/bd_49ec_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_1/bd_49ec_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_2/bd_49ec_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_3/bd_49ec_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_4/bd_49ec_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_5/bd_49ec_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_6/bd_49ec_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_7/bd_49ec_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_8/bd_49ec_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_9/bd_49ec_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_10/bd_49ec_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_11/bd_49ec_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_12/bd_49ec_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_13/bd_49ec_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_14/bd_49ec_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_15/bd_49ec_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_16/bd_49ec_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_17/bd_49ec_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_18/bd_49ec_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_19/bd_49ec_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_20/bd_49ec_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_21/bd_49ec_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_22/bd_49ec_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_23/bd_49ec_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_24/bd_49ec_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_25/bd_49ec_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_26/bd_49ec_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_27/bd_49ec_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_28/bd_49ec_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_29/bd_49ec_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_30/bd_49ec_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_31/bd_49ec_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_32/bd_49ec_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_33/bd_49ec_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_34/bd_49ec_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_35/bd_49ec_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_36/bd_49ec_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_37/bd_49ec_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_38/bd_49ec_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_neural_network_0_3/design_1_neural_network_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_neural_network_0_3 || ORIG_REF_NAME==design_1_neural_network_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_1/design_1_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_1 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_2/design_1_processing_system7_0_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_2 || ORIG_REF_NAME==design_1_processing_system7_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_2/design_1_proc_sys_reset_0_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_2 || ORIG_REF_NAME==design_1_proc_sys_reset_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_1/bd_49ec_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_2/bd_49ec_arsw_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_3/bd_49ec_rsw_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_4/bd_49ec_awsw_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_5/bd_49ec_wsw_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_6/bd_49ec_bsw_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_10/bd_49ec_s00a2s_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_11/bd_49ec_sarn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_12/bd_49ec_srn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_13/bd_49ec_sawn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_14/bd_49ec_swn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_15/bd_49ec_sbn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_19/bd_49ec_s01a2s_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_20/bd_49ec_sarn_1_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_21/bd_49ec_srn_1_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_22/bd_49ec_sawn_1_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_23/bd_49ec_swn_1_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_24/bd_49ec_sbn_1_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_25/bd_49ec_m00s2a_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_26/bd_49ec_m00arn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_27/bd_49ec_m00rn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_28/bd_49ec_m00awn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_29/bd_49ec_m00wn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_30/bd_49ec_m00bn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_32/bd_49ec_m01s2a_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_33/bd_49ec_m01arn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_34/bd_49ec_m01rn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_35/bd_49ec_m01awn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_36/bd_49ec_m01wn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/bd_0/ip/ip_37/bd_49ec_m01bn_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_3/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_3 || ORIG_REF_NAME==design_1_smartconnect_0_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: g:/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/design_1_ooc.xdc
