# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/pratyush/Downloads/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/constrs_1/new/design.xdc

# Block Designs: C:/Users/pratyush/Downloads/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.srcs/sources_1/bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# XDC: c:/Users/pratyush/Downloads/zed_board/F/Vivado_projects/Pynq/Pynq_handwritten_digit_recognition.gen/sources_1/bd/design_1/design_1_ooc.xdc
